const products = [
    {
        'id': '1',
        'name': 'Smartphone X12',
        'image': '/images/smartphone-x12.jpg',
        'description': 'Un smartphone de última generación con pantalla AMOLED y gran rendimiento.',
        'brand': 'TechBrand',
        'category': 'Electronics',
        'price': 699.99,
        'countInStock': 15,
        'rating': 4.5,
        'numReviews': 120,
    },
    {
        'id': '2',
        'name': 'Laptop Pro 15',
        'image': '/images/laptop-pro-15.jpg',
        'description': 'Una laptop potente para profesionales con diseño ultraligero.',
        'brand': 'WorkTech',
        'category': 'Computers',
        'price': 1299.99,
        'countInStock': 7,
        'rating': 4.8,
        'numReviews': 85,
    },
    {
        'id': '3',
        'name': 'Auriculares Noise-Cancel',
        'image': '/images/noise-cancel-headphones.jpg',
        'description': 'Auriculares con cancelación de ruido activa y sonido de alta calidad.',
        'brand': 'SoundMaster',
        'category': 'Accessories',
        'price': 199.99,
        'countInStock': 25,
        'rating': 4.3,
        'numReviews': 65,
    },
    {
        'id': '4',
        'name': 'Monitor UltraWide',
        'image': '/images/ultrawide-monitor.jpg',
        'description': 'Monitor ultra ancho ideal para multitarea y edición de video.',
        'brand': 'VisionTech',
        'category': 'Displays',
        'price': 399.99,
        'countInStock': 10,
        'rating': 4.7,
        'numReviews': 50,
    },
    {
        'id': '5',
        'name': 'Teclado Mecánico RGB',
        'image': '/images/mechanical-keyboard-rgb.jpg',
        'description': 'Teclado mecánico con iluminación RGB personalizable y diseño ergonómico.',
        'brand': 'GameGear',
        'category': 'Peripherals',
        'price': 89.99,
        'countInStock': 30,
        'rating': 4.6,
        'numReviews': 70,
    },
    {
        'id': '6',
        'name': 'Cámara ActionCam',
        'image': '/images/actioncam.jpg',
        'description': 'Cámara resistente al agua ideal para deportes extremos y aventuras.',
        'brand': 'AdventurePro',
        'category': 'Cameras',
        'price': 249.99,
        'countInStock': 12,
        'rating': 4.4,
        'numReviews': 95,
    },
];
  
export default products;
